config/routes.rb
Rails.application.routes.draw do
  get '/poems' ,to: 'poems#index'

  get '/login',to: 'sessions#new'
  post '/login',to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'

  get '/signup' ,to:'users#new'
  get '/index', to: 'users#index'

  root 'poems#index'
  get '/about' ,to: "static_page#about"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :poems
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poem.rb
class Poem < ApplicationRecord
  belongs_to :user
  
  validates :user_id, presence: true
  validates :first, presence: true, length: {minimum: 3, maximum: 8}
  validates :second, presence: true, length: {minimum: 3, maximum: 8}
  validates :third, length: {maximum: 6}
end

app/models/user.rb
class User < ApplicationRecord
    has_many :poems
    before_save { email.downcase! }
    validates :name ,presence: true, length: {maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email ,presence: true, length: {maximum:255},
                      format: {with: VALID_EMAIL_REGEX},
                      uniqueness: {case_sensitive: false}
                      
    has_secure_password
    validates :password,presence: true, length: {minimum: 6}, allow_nil: true
    
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   include SessionsHelper
   include PoemsHelper
   
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :log_in, only: [:new,:create,:edit,:upate,:destroy]
  before_action :destroyable, only: [:destroy]
  before_action :editable, only: [:edit, :update] 
  
  
  
  def index
    @poems = Poem.where(parent_id: nil).paginate(page: params[:page],per_page:3)
    .order(id: "desc")
  end
  
  def show
    @poem = Poem.find_by(id: params[:id])
    if @poem.parent_id
      @poem =  Poem.find_by(id: @poem.parent_id)
    end
    @subsidiary_poems = Poem.where(parent_id: @poem.id)
  end
  
  def new
    if params[:parent_id]
      @parent_poem = Poem.find_by(id: params[:parent_id])
      if @parent_poem.finish
        flash[:notice] = "この作品はすでに完成にしてます"
        redirect_to @parent_poem
      end
      @poem= current_user.poems.build(parent_id: params[:parent_id])
    else
      @poem= current_user.poems.build(parent_id: nil)
    end
  end
  
  def create
    @parent_poem = Poem.find_by(id: params[:parent_id])
    if !@parent_poem.nil?
      if @parent_poem.finish
        flash[:notice] = "この作品はすでに完成にしてます"
        redirect_to @parent_poem
      end
    end
    
    @poem= current_user.poems.build(poem_params)
    if @poem.save
      if @poem.finish
        @parent_poem = Poem.find_by(id: @poem.parent_id)
        if @parent_poem
          @parent_poem.finish = true
          if @parent_poem.save
          end
        end
      end
      flash[:success] = '作成成功'
      redirect_to @poem
    else
      flash.now[:danger] = '入力内容が間違っています。'
      render 'new'
    end
    
  end
  
  def edit
    @poem = Poem.find_by(id: params[:id])
  end
  
  def update
    @poem = Poem.find_by(id: params[:id])
    if @poem.update_attributes(poem_params)
      flash[:success] = "編集成功"
      redirect_to @poem
    else
      flash[:danger] = "入力内容に間違いがあります"
      render 'edit'
    end
  end
  
  def destroy
    @poem = Poem.find_by(id: params[:id])
    parent_id = @poem.parent_id
    Poem.find_by(id: params[:id]).destroy
    flash[:success] = '削除成功'
    if !parent_id.nil?
      redirect_to Poem.find_by(id: parent_id)
    else
      redirect_to poems_url
    end
  end
  
  private
    def poem_params
      params.require(:poem).permit(:first, :second, :third,:parent_id, :finish)
    end
    
    def log_in
      if current_user.nil?
        flash[:notice] = "ログインしてください"
        redirect_to login_path
      end
    end
    
    def destroyable
      @poem = Poem.find_by(id: params[:id])
      unless allow_destroy(@poem)
        flash[:notice] = "権限がありません"
        redirect_to poems_url
      end
    end
    
    def editable
      @poem = Poem.find_by(id: params[:id])
      unless allow_edit(@poem)
        flash[:notice] = "権限がありません"
        redirect_to poems_url
      end
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:sessions][:email])
    if user && user.authenticate(params[:sessions][:password])
      log_in user
      flash[:success] = "ログインしました。"
      redirect_to user
    else
      flash.now[:danger] = "入力情報が間違っています。"
      render 'new'
    end
  end
  
  def destroy
    logout
    redirect_to poems_url
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: [:index, :edit, :update,:destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user?,     only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find_by(id: params[:id])
    @user_poems = @user.poems.where(parent_id: nil).paginate(page: params[:page],per_page:2)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "登録完了"
      log_in(@user)
      redirect_to @user
    else
      flash[:danger] = "入力項目が間違っています"
      render 'new'
    end
  end
  
  def edit
    @user = User.find_by(id: params[:id])
  end
  
  def update
    @user = User.find_by(id: params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "編集完了"
      redirect_to @user
    else
      flash[:danger] = "入力項目が間違っています"
      render 'edit'
    end
  end
  
  def destroy
    User.find_by(id: params[:id]).destroy
    flash[:notice] = 'ユーザーを削除しました。'
    redirect_to users_path
  end
  
  private
    def user_params
      params.require(:user).permit(:name,:email, :password,:password_confirmation)
    end
    
    def logged_in?
      unless log_in?
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end
    
    def correct_user
      user = User.find_by(id: params[:id])
      unless current_user.id == user.id
        flash[:danger] = "編集権限がありません"
        redirect_to user_path(current_user)
      end
    end
  
    
    def admin_user?
      redirect_to root_url unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title='')
    base_title = "Poem App"
    if title.empty?
      base_title
    else
      title + ' | ' + base_title
    end
  end
  
  
end

app/helpers/poems_helper.rb
module PoemsHelper
  
  def finish_poem(poem)
    parent_poem = Poem.find_by(id: poem.parent_id)
    if parent_poem.nil?
      poem.finish
    else
      parent_poem.finish
    end
      
      
  end
  
  def allow_destroy(poem)
    if current_user.admin || 
      (current_user.id == poem.user.id && !finish_poem(poem))
      true
    else
      false
    end
  end
  
  def allow_edit(poem)
    if !finish_poem(poem) && current_user.id == poem.user.id
      true
    else
      false
    end  
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def log_in?
    !current_user.nil?
  end
  
  def current_user?(user)
    current_user.id == user.id
  end
 
  def logout
    session[:user_id] = nil
    @current_user = nil
  end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
    
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <%= link_to image_tag("app_logo.png", size:"120x120"), root_path %>
  <ul class=link>
    <li class="header-link"><%= link_to 'ホーム', root_path %></li>
    <li class="header-link"><%= link_to '使い方', about_path %></li>
    <li class="header-link"><%= link_to '作品一覧', poems_path %></li>
    <% if log_in? %>
      <li class="header-link"><%= link_to 'ユーザー一覧', index_path %></li>
      <li class="header-link"><%= link_to "新しく投稿する",new_poem_path%></li>
      <li class="header-link"><%= link_to current_user.name, @current_user %></li>
      <li class="header-link"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
   
    <% else %>
      <li class="header-link"><%= link_to 'ログイン', login_path %></li>
      <li class="header-link"><%= link_to '新規登録', signup_path %></li>
    <% end %>
  </ul>
</header>

app/views/layouts/_question_show.html.erb
<h2>題名:<%=@question.title %></h2>
   <p>作者:<%=@question.auther %></p>
  <p>Level:<%=@question.level %></p>
  <p>正答率:<%= accurate_rate(@question)%>%</p>

  <p>本文1:</p>
  <p><%=@question.main_text1 %></p>
  <p>本文2:</p>
  <p><%=@question.main_text2 %></p>
  <p>本文3:</p>
  <p><%=@question.main_text3 %></p>
  <p>問:<%=@question.question %></p>
  <p>選択肢</p>
  <p>1:<%=@question.choice1 %></p>
  <p>2:<%=@question.choice2 %></p>
  <p>3:<%=@question.choice3 %></p>
  <p>4:<%=@question.choice4 %></p>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=full_title(yield(:title))%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class='wrapper'>
      <div class='container'>
       <%= render 'layouts/flash' %>
       <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/poems/_poem.html.erb
<li class="poem">
  <p class="poem-user">投稿者:<%= link_to poem.user.name, poem.user%></p>
  <%= link_to poem do%>
    <h3><%= poem.first%></h3>
    <h3><%= poem.second%></h3>
    <% if poem.third%><h3><%= poem.third %></h3><% end %>
  <% end %>
    <p><%= poem.created_at%></p>
    <p><%= poem.updated_at%></p>
    <% if log_in?%>
      <% if allow_edit(poem)%>
        <%= link_to "編集", edit_poem_path(poem) %>
      <% end %>
      <% if allow_destroy(poem)%>
         <%= link_to "削除", poem, method: :delete, data: {comfirm:'本当に削除しますか？'}%>
      <% end %>
    <% end %>
    <% if yield(:title) == "All poems"%>
      <p>状態:
        <%if poem.finish%>
         完成
        <%else%>
        作成中
        <%end%>
      <p>
    <% end%>
    
</li>

app/views/poems/_poem_form.html.erb
<div class="input-form">
  <%= form_for(@poem) do |f|%>

    <% if @poem.errors.any? %>
      <% @poem.errors.full_messages.each do |message|%>
        <li class="data-error"><%= message%></li>
      <% end %>
    <% end %>

    <%= f.label :first ,"第一句"%>
    <%= f.text_field :first%>
    
    <%= f.label :second ,"第二句"%>
    <%= f.text_field :second%>
    
    <%= f.label :third ,"第三句"%>
    <%= f.text_field :third%>

    <%= f.label :parent_id,"発句のID"%>
    <%= f.number_field :parent_id, readonly: true%>

    <%= f.label :finish ,"完成"%>
    <%= f.check_box :finish, :as=>:boolean%>
  
    <%= f.submit yield(:btn)%>
  <%end%>
  
  <p>
    第一句を５ 第二句を７ 第三句を５ または第一句を７ 第二句を７としてお使いください
  </p>
  <p>
  漢字での入力、また字余りを考慮して第一句を３～８　第二句を３～８　第三句を０～６文字まで入力できます。</p>
  <p>
  完成にチェックをして送信すると発句から自分の投稿に至るまで編集と削除ができなくなります。</p>
</div>

app/views/poems/_user_form.html.erb
<div class="input-form">
  
  <%= form_for(@user) do |f|%>

    <% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |message|%>
        <li class="data-error"><%= message%></li>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name%>

    <%= f.label :email%>
    <%= f.text_field :email%>

    <%= f.label :password%>
    <%= f.password_field :password%>

    <%= f.label :password_confirmation%>
    <%= f.password_field :password_confirmation%>
  
    <%= f.submit yield(:btn)%>
  <%end%>
</div>

app/views/poems/edit.html.erb
<% provide(:title, "Poem Edit")%>
<% provide(:btn, '編集')%>


  <h1>編集</h1>
  <%= render "poem_form"%>

app/views/poems/index.html.erb
<% provide(:title, "All poems")%>

  <h1>作品一覧</h1>


 <%= will_paginate %>
    <ul class="users">
      <% @poems.each do |poem| %>
        <%= render 'poem', { poem: poem }%>
      <% end %>
    </ul>
  <%= will_paginate %>
  
　<% if log_in?%>
    <%= link_to "新しく投稿する",new_poem_path%>
  <% end %>

app/views/poems/new.html.erb
<% provide(:title, 'Create')%>
<% provide(:btn, '作成')%>

  <%= render "poem_form"%>

app/views/poems/show.html.erb
<% provide(:title, "Poem Show" )%>

  <ul class="users">
    <%= render 'poem', {poem: @poem}%>
  <ul>        
  <ul>
      <% @subsidiary_poems.each do |subpo|%>
        <%= render 'poem', {poem: subpo}%>
      <% end %>
  </ul>
  <% unless @poem.finish%>
    <%= link_to '続きを投稿する', new_poem_path(parent_id: @poem.id)%>
  <% end %>
  <%= link_to '一覧に戻る', poems_path%>

app/views/static_page/about.html.erb
<% provide(:title, "About")%>

       　<div class="row">
         <h1>連歌Appの使い方</h1>
  <p>これは連歌アプリです</p>
  <p>自分の、あるいは他の人が書き始めた和歌に続きを書いていくことでみんなで一つの連歌を作ることができます</p>
  <br>
  <h2>ログインしていない場合</h2>
    <p>新規ユーザー登録は<%= link_to 'こちら', signup_path %>こちら</p>
    <p>すでにアカウントをお持ちの方は<%= link_to 'こちら', login_path%></a></p>
  <br>
  <h2>ログインしている場合</h2>
    <p>ログインしている場合は新しく投稿する、作品一覧から作成中の作品の続きを作ることができます</p>
  <h2>手順</h2>
  <h3>新しく作品を作る場合</h3>
    <p>①「新しく投稿」で「第一連」「第二連」「第三連」を入力すると「作品一覧」に送信されます</p>
    <p>「第一連」は３～８文字「第二連」は３～８文字「第三連」は０～６文字で投稿することができます</p>
    <p> 「完成」をチェックするとその作品は完成したことになり、以降、編集削除は不可能になります
    <p>②「作品一覧」に他の人のをふくめた作品(発句)が並んでいます</p>
    <p>その中で自分が見たいものや描きたいものをクリックします</p>
    <p>③開くと作品の発句と以降の句、そして作成中の作品は続きを投稿するボタンが出てきます</p>
    <p>「続きを書く」を押すとそれまでの続きから自分が文章を書くことができます</p>
    <p>以降の説明は①に戻ります</p>
  <h3>注意事項</h3>
    <p>※他人への誹謗中傷、その他他人を不快にさせる内容は管理人によって削除される
    可能性があります</p>

       　
       　</div>
　<% unless log_in?%>
　  <h3><%= link_to '登録する',signup_path%><h3>
　<% end%>

app/views/users/_user_form.html.erb
<div class="input-form">
  
  <%= form_for(@user) do |f|%>

    <% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |message|%>
        <li class="data-error"><%= message%></li>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name%>

    <%= f.label :email%>
    <%= f.text_field :email%>

    <%= f.label :password%>
    <%= f.password_field :password%>

    <%= f.label :password_confirmation%>
    <%= f.password_field :password_confirmation%>
  
    <%= f.submit yield(:btn)%>
  <%end%>
</div>

app/views/users/edit.html.erb
<% provide(:title, "#{@user.name} Info Edit")%>
<% provide(:btn, '編集')%>

  <h1>編集</h1>
  <%= render "user_form"%>

app/views/users/index.html.erb
<% provide(:title, "All users")%>


  <h1>ユーザー</h1>

  <%= will_paginate %>

    <ul class="users">
      <% @users.each do |user| %>
        <li>
          <%= link_to user.name, user %>
          <% if current_user.admin? && !current_user?(user)%>
          | <%= link_to "削除", user, method: :delete, data: {comfirm:'本当に削除しますか？'}%>
          <% end %>
        </li>
      <% end %>
    </ul>

  <%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up')%>
<% provide(:btn, '登録')%>

  <h1>登録</h1>
 
  <%= render "user_form"%>

app/views/users/show.html.erb
<% provide(:title, @user.name )%>

  <h1>名前:<%= @user.name%></h1>
  <% if current_user?(@user)%>
    <%= link_to "ユーザー情報編集", edit_user_path(@user.id)%>
  <% end%>
　<h1>　</h1>
  <h1>発句一覧</h1>

    <%= will_paginate @user_poems%>
      <% @user_poems.each do |poem| %>
        <%= render 'poems/poem', { poem: poem }%>
          <p>状態:
          <%if poem.finish%>
          完成
          <%else%>
          作成中
          <%end%>
          </p>
        <% end%>
    <%= will_paginate @user_poems %>